server:
  shutdown: graceful

management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: info,health,metrics,prometheus

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: spring-kafka-sample
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    streams:
      application-id: spring-kafka-sample-stream

kafka:
  topic: com.canyapan.sample.my-topic
  topic2: com.caxnyapan.sample.my-topic2
